name: erle-date-file.erle
vendor: Erle Robotics <contact@erlerobot.com>
icon: meta/erle-small.png
version: 1.0
architecture: armhf
binaries:
 - name: src/script.sh
maintainer: Víctor Mayoral <victor@erlerobot.com>
